### PR TITLE
Fix for falsely reporting do-whiles as an error

### PR DESCRIPTION
**Pull request by alexhenning**
Addresses issue https://github.com/ros/roslint/issues/31

### CODE REVIEW

**Comment by mikepurvis** [comment]
This looks reasonable; we should figure out how to add some test logic to cover these modifications— would also make it more possible to pull in updated versions of `cpplint.py`.

**Comment by alexhenning** [comment]
@mikepurvis What kind of tests are you thinking? We could collect a number of files like the one in issue #31 and #32 with known outputs and verify that the output is what we expect. Unfortunately, this would be a sensitive to changes in the message text. However, the tests would at least indicate which messages had changed and could be updated when cpplint was updated.

**Comment by jack-oquin** [comment]
That sounds reasonable to me. 

Perhaps the tests could use some regexps to lessen the dependency on exact message output. Maybe they could parse the error numbers.

**Comment by mikepurvis** [comment]
I'd be fine with just supplying test cases that are known-pass/known-fail. The specifics of the error message are less important than having a small body of code against which the whole thing can be smoke-tested.

**Comment by jack-oquin** [comment]
+1 to Mike's pass/fail idea.

**Comment by alexhenning** [comment]
I created issue https://github.com/ros/roslint/issues/36 to track adding tests, lets continue the discussion there.

**Pull request merged**
